# netlify.toml - Configuración corregida

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co"

# Proteger archivos sensibles
[[redirects]]
  from = "/.env"
  to = "/404"
  status = 404

[[redirects]]
  from = "/.git/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/config/*"
  to = "/404"
  status = 404

# REDIRECCIONES DE PÁGINAS ESPECÍFICAS (sin login)
[[redirects]]
  from = "/index.html"
  to = "/login.html"
  status = 302
  force = true

[[redirects]]
  from = "/historial.html"
  to = "/login.html"  
  status = 302
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/login.html"
  status = 302
  force = true

# PÁGINA PRINCIPAL = LOGIN
[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200

# 404 personalizado (DEBE IR AL FINAL)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404