# netlify.toml - Configuración corregida

# Headers de seguridad - CORREGIDOS PARA SUPABASE
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://*.supabase.co; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co https://gtogelwnsbgodwfghhku.supabase.co; img-src 'self' data: https:;"

# Proteger archivos sensibles
[[redirects]]
  from = "/.env"
  to = "/404"
  status = 404

[[redirects]]
  from = "/.git/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/config/*"
  to = "/404"
  status = 404

# PÁGINA PRINCIPAL = LOGIN (solo la raíz)
[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200

# 404 personalizado (DEBE IR AL FINAL)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404